### PR TITLE
TypeScript Migration: The Good

### PR DESCRIPTION
**Pull request by jens-ox**
This PR migrates the easy-to-migrate files and classes to TypeScript. Additionally, this serves as a test that the docs etc. still work.

### Docs

JSDoc will technically still work with TypeScript files, but makes little to no sense as all types would need to be defined both in JSDoc and in TypeScript. Instead, I would suggest to use [TSDoc](https://tsdoc.org/) (which is pretty buch identical to JSDoc) and [TypeDoc](https://typedoc.org/) as a replacement.

You can try out the new docs by running `npm run docs:ts`.

### Remaining Work

The remaining files are a bit more complex to migrate, so I created separate PRs per file to make reviewing the changes easier. They depend on the migration of other files:

```mermaid
flowchart LR;

A[This PR];
B[#778];
C[#780];
D[#781];
E[#782];
F[#783];

    A-->B;
    B-->C;
    C-->D;
	D-->E;
	E-->F;
```

- `niivue/index.js`
- ✅ `nvimage/index.js` #783 
- ✅ `nvconnectome.js` #780 
- ✅ `nvcontroller.js` #781 
- ✅ `nvdocument.js` #782 
- ✅ `nvmesh.js` #778

### CODE REVIEW

**Comment by hanayik** [comment]
I have a feeling we are going to see “the bad” and “the ugly” at some point as well 🤣

**Comment by jens-ox** [comment]
@hanayik, yes, those will come - see https://github.com/jens-ox/niivue/pull/7 for a sneak peek 😅

**Comment by jens-ox** [comment]
@hanayik @neurolabusc 

I would consider this PR to be ready for review. The remaining files will be a bit uglier to migrate.

**Comment by hanayik** [comment]
@jens-ox , great! I’ll aim to take a look over the next couple of days.

**Comment by jens-ox** [comment]
@hanayik great! I will also open separate PRs for the more complex files.

**Pull request merged**
