### PR TITLE
Linting setup

### PR DESCRIPTION
**Pull request by jens-ox**
Hi all!

This PR updates the linting setup to use a stricter ESLint configuration. Specifically, it integrates Prettier into ESLint (which was already installed but was invoked by the build script) and uses the [JavaScript Standard Style](https://standardjs.com/). I also added linting to the CI action.

This should catch a couple of common gotchas, e.g. #739.

The second commit of this PR includes all changes caused by running `eslint --fix .`, reducing the amount of "errors" from ~16.5k to ~1k. The remaining "errors" require manual work, which I would do if the changes to the linting setup introduced by this PR are ok for everyone.

### CODE REVIEW

**Comment by jens-ox** [comment]
@hanayik @neurolabusc does this linting setup make sense for you? If the config is ok, I would start addressing the linting issues that need manual fixing.

**Comment by neurolabusc** [comment]
Looks good to me. @hanayik has been maintainer of these features so may have strong opinions.

**Comment by jens-ox** [comment]
@neurolabusc @hanayik I tried to separate the different types of issues into different commits. I marked the non-trivial ones with `[nontrivial]` - those are probably the only commits worth looking at.

13 problems remain that require more knowledge of the code than I have, all are in `nvmesh-loaders.js`. It would be great if someone could have a look at them, this PR is ready otherwise.

CleanShot 2023-11-19 at 15 44 03@2x

**Comment by jens-ox** [comment]
@neurolabusc could you approve the workflow run?

**Review by hanayik — COMMENTED** [review]
@jens-ox , by switching to `hasOwn` aren't we dropping [support](https://caniuse.com/?search=hasOwn) for many browser versions released prior to 2021/2022 (based on the browser)? For example, we support Safari `15`+ because it added WebGL2 support without being an experimental flag, but `hasOwn` was introduced in Safari `15.4`, so that would now be the lowest supported version right?

**Review by hanayik — APPROVED** [review]

**Review by hanayik — CHANGES_REQUESTED** [review]
@jens-ox, there's a problem with loading some image formats that I need to track down. For example, the image `<project_root>/tests/images/FLAIR.nrrd` won't load via drag and drop, along with the `enh.dcm` image in the same directory. They load ok from URL, just not drag and drop

**Comment by jens-ox** [comment]
@hanayik 
> by switching to hasOwn aren't we dropping [support](https://caniuse.com/?search=hasOwn) for many browser versions released prior to 2021/2022 (based on the browser)? For example, we support Safari 15+ because it added WebGL2 support without being an experimental flag, but hasOwn was introduced in Safari 15.4, so that would now be the lowest supported version right?

I reverted this again in https://github.com/niivue/niivue/pull/743/commits/1ddb5fde931ce065f1a12f35c1cc076175840d22, has `hasOwn` (or `hasOwnProperty`) wasn't really needed. Those comparisons can be further simplified once a port to TS starts.

> there's a problem with loading some image formats that I need to track down. For example, the image <project_root>/tests/images/FLAIR.nrrd won't load via drag and drop, along with the enh.dcm image in the same directory. They load ok from URL, just not drag and drop

How can I test this?

**Comment by hanayik** [comment]
@jens-ox , yep, unfortunately there are no tests for drag and drop file loading (could just as easily be a file input element in testing). I’ll keep investigating this during the morning.

**Comment by jens-ox** [comment]
@hanayik I also investigated for a bit this morning but wasn't able to resolve it. Should this be fixed in this PR or in a follow-up?

**Comment by hanayik** [comment]
Since the existing tests pass, and this PR is already large enough, I’ll merge it now, and then address the file loading issue via drag and drop

**Pull request merged**
