### PR TITLE
Fall back to QForm if set (https://github.com/niivue/niivue/issues/243)

### PR DESCRIPTION
**Pull request by neurolabusc**
1. Related to [issue 243](https://github.com/niivue/niivue/issues/243). This PR will default to the QForm if the QForm code exceeds the SForm code. In case of ties, precedence is for SForm. This could be extended to allow the user to override the SForm with the QForm (e.g. ITK defaults). 

Here the change is specific to NiiVue, but @cdrake may want to evaluate if this could be added to the logic of [NIFTI-Reader-JS](https://github.com/rii-mango/NIFTI-Reader-JS) to help other tools that use this useful core library.

2. Includes a patch for old versions of [fmriprep](https://github.com/nipreps/fmriprep/issues/2507) that would set the scl_slope and scl_inter to `not a number`. Again, this would be a useful contribution to NIFTI-Reader-JS.

@vincenzoml can test if these work with his images.

One can make test images with [nii_tool](https://github.com/xiangruili/dicm2nii). I used examples from [here](https://github.com/rordenlab/NIfTIspace):

```
fslorient -copysform2qform SPL.nii.gz
nii = nii_tool('load', 'SPL.nii.gz')
nii.hdr.sform_code = 0;
nii.hdr.srow_x = [0 0 0 0]
nii.hdr.srow_y = [0 0 0 0]
nii.hdr.srow_z = [0 0 0 0]
nii_tool('save', nii, 'qform.nii')
 ```

### CODE REVIEW

**Comment by cdrake** [comment]
I can sumbit a PR to [NIFTI-Reader-JS](https://github.com/rii-mango/NIFTI-Reader-JS). My last PR has not been merged.

**Comment by vincenzoml** [comment]
I'd like to test the patch but being a bit new to javascript I don't exactly know how to do this (I just have a project where I added niivue with yarn add; can I add a patch directly in my source tree?)

**Comment by hanayik** [comment]
> I'd like to test the patch but being a bit new to javascript I don't exactly know how to do this (I just have a project where I added niivue with yarn add; can I add a patch directly in my source tree?)

It would be quite messy to to do that. if you ever want to use the "bleeding edge" you could checkout the Niivue git repo and then `npm link` into your project. However, that's not the cleanest way to do things. I usually just `npm link` for testing my own unpublished code. 

I will release a new NiiVue version on npm in a few min.

**Comment by hanayik** [comment]
you can see the status here: 

https://github.com/niivue/niivue/runs/5276863270?check_suite_focus=true

**Comment by hanayik** [comment]
@vincenzoml, You can now get the latest version.

https://www.npmjs.com/package/@niivue/niivue

**Comment by vincenzoml** [comment]
The patch solves my issue, thanks a lot as usual.

**Pull request merged**
