### PR TITLE
Diverging colors, mesh alphaThreshold

### PR DESCRIPTION
**Pull request by neurolabusc**
List of fixed issues (if they exist):

- [issue 608](https://github.com/niivue/niivue/issues/608)

### CODE REVIEW

**Comment by hanayik** [comment]
@neurolabusc , I suspect the tests will pass now. I ran `npm run test` locally to generate the new snapshots for additional colormaps. Now the GitHub actions job will not fail due to not having those particular snapshots.

**Comment by hanayik** [comment]
@neurolabusc , the windows tests seem to be failing (not related to this PR). They don’t seem happy with the AFNI file loader test for some reason:

https://github.com/niivue/niivue/actions/runs/5136979649/jobs/9244435051?pr=609#step:7:165

I suspect this was always the case but we didn’t know until the file loader test suite was expanded. I suggest we merge this PR in now, and submit a new issue and PR for the AFNI file loader tests fix on windows.

**Comment by neurolabusc** [comment]
@hanayik remember that web pages live in a sandbox, so for dual-file formats like HEAD/BRIK you need to specify ***both*** files. [Here us an example](https://niivue.github.io/niivue/features/afni.html):

```
      url: "../images/example4d+orig.HEAD", //"./images/RAS.nii.gz", "./images/spm152.nii.gz",
      urlImgData: "../images/example4d+orig.BRIK.gz",
```

The [test.fileFormats.js](https://github.com/niivue/niivue/blob/fd1d35ce853b41e35860d67d1de6a847e47614d7/tests/test.fileFormats.js#LL42C9-L42C12) is only specifying the `url`, not the `urlImgData`.

**Comment by hanayik** [comment]
We treat HEAD as a special case when loading from URL and automatically search for BRIK at the same location. 

https://github.com/niivue/niivue/blob/fd1d35ce853b41e35860d67d1de6a847e47614d7/src/nvimage.js#L2786

and that doesn’t explain why it only fails on windows. Perhaps related to the line-by-line parsing of the HEADer? I’m on mobile, but can investigate more later.

**Pull request merged**
