### PR TITLE
add an ROI-based colormap from AFNI

### PR DESCRIPTION
**Pull request by mrneont**
List of fixed issues (if they exist):

-
-
-

### CODE REVIEW

**Comment by neurolabusc** [comment]
You should change:
```  
"min": 0,
  "max": 255,
```
to read
```  
"min": 0,
 "max": 0,
```
This refers to the voxel intensity for the first and last index in your colormap. Since MR scans have relative intensities, you should not specify this. NiiVue will default to the [robust range](https://fsl.fmrib.ox.ac.uk/fsl/fslwiki/Fslutils) for voxel intensities unless the NIfTI header or color table specify otherwise (and the user can interactively adjust this by dragging over a 2D slice).

**Comment by hanayik** [comment]
@mrneont, is this PR still a work in progress?

**Comment by mrneont** [comment]
@hanayik : I (think I) am happy with those cmaps if you are!  Those should be the main ones for the APQC HTML, at present (you already have a Plasma cmap in the distribution).

**Comment by neurolabusc** [comment]
Looks good to me.

**Pull request merged**
