### PR TITLE
Add tests with gifti files generated using nibabel

### LINKED ISSUE #507: XML files are not read properly in NVMesh
Linked to https://github.com/nilearn/nilearn/issues/3451#issuecomment-1416174323

**Summary**
It seems that XML files are not read properly by `NVMesh` methods because they read XML files line by line.
In particular, `NVMesh.readGII()` can't read gifti files generated with `nibabel` (and probably a lot of other gifti files).

**The specific case of `NVMesh.readGII()`**
Here are 2 issues I spotted for `NVMesh.readGII()` :
- it reads xml files line by line, which prevents it from reading base64 data when it's not stored in a line of its own
- it doesn't handle float64 arrays

Here is a python snippet which will create a valid gifti file which `niivue` can't read:

```python
# %% make_surface.py
import pathlib

import nibabel as nib

from nilearn import datasets, surface

fsaverage = datasets.fetch_surf_fsaverage("fsaverage7")

motor_images = datasets.fetch_neurovault_motor_task()
stat_img = motor_images.images[0]
surface_map = surface.vol_to_surf(stat_img, fsaverage.pial_left)

surface_map_path = "./surface_map.gii"

img = nib.gifti.gifti.GiftiImage()
img.add_gifti_data_array(
    nib.gifti.gifti.GiftiDataArray(
        surface_map,
        intent="NIFTI_INTENT_ZSCORE",
    )
)
nib.save(img, surface_map_path)
```

The generated file looks something like this:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE GIFTI SYSTEM "http://www.nitrc.org/frs/download.php/115/gifti.dtd">
<GIFTI Version="1.0" NumberOfDataArrays="1"><MetaData /><LabelTable /><DataArray Intent="NIFTI_INTENT_ZSCORE" DataType="NIFTI_TYPE_FLOAT64" ArrayIndexingOrder="RowMajorOrder" Dimensionality="1" Encoding="GZipBase64Binary" Endian="LittleEndian" ExternalFileName="" ExternalFileOffset="0" Dim0="163842"><MetaData /><CoordinateSystemTransformMatrix><DataSpace>NIFTI_XFORM_UNKNOWN</DataSpace><TransformedSpace>NIFTI_XFORM_UNKNOWN</TransformedSpace><MatrixData>  1.000000   0.000000   0.000000   0.000000
  0.000000   1.000000   0.000000   0.000000
  0.000000   0.000000   1.000000   0.000000
  0.000000   0.000000   0.000000   1.000000</MatrixData></CoordinateSystemTransformMatrix><Data>...</Data></DataArray></GIFTI>
```

But as `NVMesh.readGII()` reads it line by line and [loads data only if it comes across a line which starts with `"<Data>"`](https://github.com/niivue/niivue/blob/f9c3849554a83f4028f91f4c440537ff5f526ef3/src/nvmesh.js#L3063), it doesn't load this file properly.
Adding a few carriage return solves this issue:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE GIFTI SYSTEM "http://www.nitrc.org/frs/download.php/115/gifti.dtd">
<GIFTI Version="1.0" NumberOfDataArrays="1">
<MetaData />
<LabelTable />
<DataArray Intent="NIFTI_INTENT_ZSCORE" DataType="NIFTI_TYPE_FLOAT64" ArrayIndexingOrder="RowMajorOrder" Dimensionality="1" Encoding="GZipBase64Binary" Endian="LittleEndian" ExternalFileName="" ExternalFileOffset="0" Dim0="163842">
<MetaData />
<CoordinateSystemTransformMatrix>
<DataSpace>NIFTI_XFORM_UNKNOWN</DataSpace><TransformedSpace>NIFTI_XFORM_UNKNOWN</TransformedSpace>
<MatrixData>  1.000000   0.000000   0.000000   0.000000
  0.000000   1.000000   0.000000   0.000000
  0.000000   0.000000   1.000000   0.000000
  0.000000   0.000000   0.000000   1.000000</MatrixData>
</CoordinateSystemTransformMatrix>
<Data>...</Data>
</DataArray></GIFTI>
```

I think the logic of `NVMesh.readGII()` needs to be reworked so that it handles gifti files which no carriage returns.
Instead of processing lines, it should probably process tags.

**Methods affected by this behaviour**
This problem is most like present in other methods as well. In particular, it seems that all functions like `NVMesh.readNII2()`, etc all have `readStrX()` and `readStr()` utility functions which read files line by line instead of tag by tag. I also checked `NVImage` quickly but couldn't really tell if this problem is present there as well.

### PR DESCRIPTION
**Pull request by alexisthual**
Related to #507.

In this PR, adds tests which fail for one current edge case of the Gifti XML parser.
In particular, it adds two tests:
1. :red_circle: a failing test parsing a gifti file generated using nibabel
2. :green_circle: a passing test parsing the same gifti file, but this time newline characters were added.

Here is the python snippet used:
```python
import nibabel as nib
import numpy as np

img = nib.gifti.gifti.GiftiImage()
img.add_gifti_data_array(
    nib.gifti.gifti.GiftiDataArray(
        np.array([1,2,3]).astype(np.float32),
        intent="NIFTI_INTENT_ZSCORE",
    )
)
nib.save(img, "test.gii")
```

This work was done with @AnthonyAndroulakis 

EDIT: the name of this branch was a bit too ambitious haha, we hadn't seen that a lot of progress had already been made regarding parsing xml files.

### CODE REVIEW

**Comment by alexisthual** [comment]
I think these tests could be of interest to you @neurolabusc as they illustrate rather simply what the parser is missing at the moment.
You can run these tests with `jest -t 'parse_xml_gifti_file'`.

**Comment by neurolabusc** [comment]
@alexisthual this PR uses the old version of the readGII(). I like you new test `test.nvmesh.js`, but please base your PR on the current version of NiiVue.

**Comment by alexisthual** [comment]
It did use an old version of `niivue`, but I thought I had rebased this branch at [6cbf34d](https://github.com/niivue/niivue/pull/528/commits/6cbf34dd70677d6862c448006684fbcd6d4ceff2). Am I missing something?

**Comment by neurolabusc** [comment]
OK

**Comment by neurolabusc** [comment]
@hanayik these tests look helpful. 

@alexisthual perhaps I can join the next nilearn NiiVue meeting and we can discuss if the current GIFTI support is sufficient. Tools like FreeSurfer have leveraged the `eXtensible` in XML, so I have tried to support their proprietary spatial transform. I also note that AFNI can support [additional datatypes not described in the specification](https://github.com/afni/afni/blob/25e77d564f2c67ff480fa99a7b8e48ec2d9a89fc/src/gifti/gifti_io.c#L167) but have never seen these in the wild. The [nibabel comments](https://github.com/nipy/nibabel/blob/14faf88feb17ec824e06972311eb0c2e16fe374f/nibabel/gifti/gifti.py#L256) also refer to usage outside of specification, but I do not have copies of those examples. So GIFTI is used both as an interchange format, but also to for a lot of tool-specific usages. Might be nice to define what features we include and what we avoid.

**Comment by hanayik** [comment]
@neurolabusc and @alexisthual, This PR is marked as a draft, so I have not merged it in.
@alexisthual, thanks for adding the tests 👍.

**Comment by alexisthual** [comment]
I just pulled `main` and ran the tests myself. Both of them are passing so I guess this PR can be merged! :blush:

**Pull request merged**
