### PR TITLE
MHA reader fixes

### PR DESCRIPTION
**Pull request by EdwinBennink**
List of fixed issues:
- MHA reader failed on reading text files with DOS line endings.
- 2D MHA images could not be read because the reader expected a 3rd dimension.
- The MHA orientation matrix was incorrectly scaled.
- For compressed paired images, the reader tried to decompress the main buffer instead of the paired image.

### CODE REVIEW

**Comment by neurolabusc** [comment]
@EdwinBennink can you provide sample [MHA format](https://itk.org/Wiki/ITK/MetaIO/Documentation) images that exhibit DOS `\r\n` rather than UNIX `\n` end of line encoding? I have never seen one in the wild.

**Comment by EdwinBennink** [comment]
Hi @neurolabusc, [this MHD/ZRAW pair](https://github.com/niivue/niivue/files/12577426/hand.zip) has DOS line endings, is 2D and uses compression in the paired ZRAW file. It is also the first time I encountered an MHA image with `\r\n` endings, but I could not find any restrictions on the line endings in the [specifications](https://itk.org/Wiki/MetaIO/Documentation) either, so I would not consider it to be 'wrong'.

**Comment by hanayik** [comment]
@EdwinBennink and @neurolabusc  , have you successfully tested that the example MHD/ZRAW file can be read and rendered by NiiVue (I have tested in ITK SNAP and it works)? I have not been able to successfully render the image in my brief trials using the `Edwinbennink:mha-reader` branch. It would also be nice to add a test for this use case so that we can ensure we don't break things during future development. I'm happy to help add the test if you can help make sure the offending image pair is renderable in NiiVue.

**Comment by EdwinBennink** [comment]
Hi @hanayik, I pushed the changes to the readMHA function, but did not push the necessary change to the NVImage class in my first commit (to actually call `readMHA` with the `pairedImgData` argument). I did that a moment ago; does it now work for you?

**Comment by hanayik** [comment]
@EdwinBennink , yes, looks good with the demo data you provided :). thanks! I will close this PR and merge in the one that I opened here that incorporates everything plus a bump in the version number #697

**Pull request closed without merging**
